name: Github Action Merge Dependabot
on: pull_request
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
