name: Github Action Merge Dependabot
on: pull_request
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
