name: Deploy Production Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build
          yarn generate

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          overwrite: true
          source: 'dist/*'
          target: '/var/www/pedronascimento.dev'
